### ISSUE TITLE
Builder not work

### ISSUE THREAD

**Issue by indraunity99** [ornberg/Sign-Language-Recognition#2]
Hi Ornberg, i am try your last code, and GUI buider is show up.
But when i want to record and select name of gesture in left GUI  i get error

_self.currentSign = self.dataset[selected[0]]
TypeError: list indices must be integers, not str_

![sc2](https://cloud.githubusercontent.com/assets/6745607/22516789/812620a6-e8d9-11e6-8622-650df83fab7b.jpg)

i think you failed to get data for number of index ? but i'm not sure because i'm new in python. 
Can you help me ? I'm trying to understand your code :)

regards

**Comment by ornberg** [comment]
No worries!

I was unable to reproduce the error.  A bug in older versions of Tkinter [returns strings for listbox selections](http://effbot.org/tkinterbook/listbox.htm#patterns) instead of integers as Tkinter 8.5 does. With your Python 2.7.0 installation, which version of Tkinter does it come with?

Converting `selected[0]` on the highlighted line in your screenshot to an int, should do the trick for now; `int(selected[0])`.
I've updated [Builder.py](https://github.com/ornberg/Sign-Language-Recognition/blob/master/Builder.py) accordingly.
However, I've only worked with Python 2.7.10 with Tkinter 8.5, so I can't guarantee there might not be another Tkinter-related issue down the road.

**Comment by indraunity99** [comment]
Hi Ornberg, 
Tkinter version is  "$Revision: 81008 $"
Now i'm downloading python 2.7.10 to try you advice.
Btw It's cool... i will try your code now 👍

**Comment by indraunity99** [comment]
Hi Ornberg, 

Builder is working fine now. 
And i try interpreter. In this case u use NB classifier to recognize right ?

can u explain this code ? 
			

> #Precompute first part of formula
> 			base = sum(map(lambda x : math.log(2 * math.pi * x), variance)) * (-0.5)_

because i get error again, ValueError: math domain error

regards

**Comment by ornberg** [comment]
Looks like you only have one sample for a class (sign), which would cause that particular class to have a per-feature `variance` of 0. Taking the `log` of 0 is undefined, which is why you get a math domain error. It shouldn't be a problem if you record more samples using `Builder.py`.

Regardless; trying to recognize hand signs with only one or two data samples is not going to give you any usable results. Try a sample size of minimum 20.

**Comment by indraunity99** [comment]
I try with 20 sample data. But the program always error.
![sc3](https://cloud.githubusercontent.com/assets/6745607/22550583/4fd423e0-e983-11e6-9fa8-5f0ece35169c.jpg)

same error 
_

> line 36, in <lambda>
> base = sum(map(lambda x : math.log(2 * math.pi * x), variance)) * (-0.5)

_

**Comment by ornberg** [comment]
Huh, that's weird. Would you mind uploading your `dataset.p` here, so I can take a look?

**Comment by indraunity99** [comment]
you can download here dude :)
https://drive.google.com/open?id=0BykIFGW7oM-ca0c3M0NidnF0enc

**Comment by ornberg** [comment]
Thanks. So, apparently, the values of palm pitch, roll and xyz positions of each sample have 0 as values for some reason (and only for the first keyframe). Unfortunately I don't have a Leap controller any more, but my old datasets do not have any zero values and I never encountered that the Leap API would output empty values.

If you want to, run [this modified version of `Builder.py`](https://drive.google.com/file/d/0Bz9r1bWx5kEGc1pNZk1pM0FUQU0), record just one sample for gesture for a class (do a hand wave or something), and upload the `output.p` so we can see what data the Leap controller is actually producing before it's compressed and flattened.

Alternatively (or additionally), you could run [this modified version of `Interpreter.py`](https://drive.google.com/open?id=0Bz9r1bWx5kEGZDE4MnpLNFVOMEk). It has a lazy fix skipping the the empty values, if you just want to test it as quick as possible.

**Comment by indraunity99** [comment]
Thanks for your respone, but i can't sent you output.p because i have error with your new code.


> File "C:\Python27\lib\lib-tk\Tkinter.py", line 1536, in __call__return 
> self.func(*args)
> 
> File "C:/Users/Master/Desktop/Development/Source/Sample/Builder.py", line 147, in stopRecording
> pickle.dump(self.vectorBuffer, open("output.p", "w+"))
> 
> File "C:\Python27\lib\pickle.py", line 1370, in dump
> Pickler(file, protocol).dump(obj)
> 
> File "C:\Python27\lib\pickle.py", line 224, in dump 
> self.save(obj)
> 
> File "C:\Python27\lib\pickle.py", line 286, in save
> f(self, obj) # Call unbound method with explicit self
> 
> File "C:\Python27\lib\pickle.py", line 600, in save_list
> self._batch_appends(iter(obj))
> 
> File "C:\Python27\lib\pickle.py", line 615, in _batch_appends
> save(x)
> 
> File "C:\Python27\lib\pickle.py", line 331, in save
> self.save_reduce(obj=obj, *rv)
> 
> File "C:\Python27\lib\pickle.py", line 419, in save_reduce
> save(state)
> 
> File "C:\Python27\lib\pickle.py", line 286, in save
> f(self, obj) # Call unbound method with explicit self
>   
> File "C:\Python27\lib\pickle.py", line 649, in save_dict
> self._batch_setitems(obj.iteritems())
>   
> File "C:\Python27\lib\pickle.py", line 663, in _batch_setitems
> save(v)
> 
> File "C:\Python27\lib\pickle.py", line 306, in save
> rv = reduce(self.proto)
>   
> File "C:\Python27\lib\copy_reg.py", line 70, in _reduce_ex
> raise TypeError, "can't pickle %s objects" % base.__name__
> TypeError: can't pickle SwigPyObject objects`

**Comment by ornberg** [comment]
Ah, shoot. Well, sorry, there's going to be a bit of a trial and error since I don't have a Leap controller to do proper testing with.

Okay, so let's try to get out the actual extract features, instead of Leap Motion objects.
Replace `utils.py` with [this modified version](https://drive.google.com/open?id=0Bz9r1bWx5kEGZW5NbUFGcEpQeTA), and use the original `Builder.py`, and then try to record another sample. Hopefully this will successfully generate an `output.p` file.

And thank you for keeping on trying this, man. Always good when people want to help out finding problems 👍

**Comment by indraunity99** [comment]
This is very fun, when you meet a programmer who will be consulted
I just want to know how the program works :)
so sorry if I'm being a bit chatty

i try utils.py and you forget to add pickle libraries :)
I fix this. 

and builder.py is working fine now and interpreter show the GUI
But if i'want to try recognize error comeback.

> Traceback (most recent call last):
>   File "C:\Python27\lib\threading.py", line 810, in __bootstrap_inner
>     self.run()
>   File "C:\Python27\lib\threading.py", line 763, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "C:/Users/Master/Desktop/Development/Source/Sample/Interpreter.py", line 123, in interpret
>     self.classify(fixedBuffer, True)
>   File "C:/Users/Master/Desktop/Development/Source/Sample/SignLanguageApp/Interpreter.py", line 68, in classify
>     if result[0][2] < 0.85: #Novelty detection based on results euclidean distance
> IndexError: list index out of range

this is [output.py](https://drive.google.com/open?id=0BykIFGW7oM-cVDBlQV9TMm1ZOGM) what do you want. I try 1 gesture with 20 record. 


once again thank you for the good response dude 👍

**Comment by ornberg** [comment]
I'm more than happy to help.
The `output.p`looked fine, all values including pitch, roll and xyz for the palm were there. 
That probably indicates that there were a hiccup of some sort the first time you built the dataset. If you deleted `dataset.p` and tried to build a new one it would hopefully work with the original `Interpreter.py` and not the modified one.

As for the `IndexError` you're getting; it tries to classify your input as fixed signs, which guessing from you dataset is what you're trying to do? ASL signs for the numbers 1-9 are fixed (static, no movement), but when you used the `Builder.py` you have set them to be gesture based signs. `Interpreter.py` uses two instances of NB classifiers, one for fixed and one for gestures. 
When you use `Interpreter.py` it determines whether your hand is moving or not and then uses the corresponding classifier. If you have no fixed signs in your `dataset.p` the classifier has no training data, and will therefore output an empty list when you do a non-moving hand sign.

So what I suggest you do again is to delete all in `dataset.p` and record them as fixed signs and try again. However, since you then will have no gesture based signs in your dataset, as soon as `Interpreter.py` detect movement and tries to classify it, the same index error will occur. I admit that there should be implemented measures to catch this earlier, but you it won't happen if you have actual gesture based signs in the dataset too (say like the ASL sign for the number 22 for instance).

![new_sign](https://cloud.githubusercontent.com/assets/19189371/22617895/c4f8d178-eacf-11e6-91c1-4d395d6141bd.png)

**Comment by indraunity99** [comment]
Thanks dude, but its still not working
I've followed your advice to make the data fixed
The new error was shown in the program

```
  File "C:/Users/Master/Desktop/Development/Source/Sample/SignLanguageApp/NBClassifier.py", line 63, in probabilities
    distances.append(self.euclidian(vector,self.classes[_class][0]) / self.classes[_class][3])
ZeroDivisionError: float division by zero
```

can you explain what the meaning about 

> self.euclidian

**Comment by ornberg** [comment]
I'm using the euclidian distance between the average and the furthest from average datapoint to determine whether a detected sign actually belongs to a class.

Would you care to upload your new `dataset.p` again, please?
I'm sorry it's not working for you :/

**Comment by indraunity99** [comment]
No problem, try and error always happens :)
I became ashamed, because so troubling
This is my dataset  [dataset.p](https://drive.google.com/open?id=0BykIFGW7oM-cQlhndG5pQnQ3UWs)
